### ISSUE TITLE
Java 9 Modular compatibility

### ISSUE THREAD

**Issue by beenham** [joffrey-bion/fx-gson#17]
Would it be possible to get Java-9 modular compatibility? The project has no module-info.java

**Comment by joffrey-bion** [comment]
Hi @beenham , thanks for your comment.
I can certainly look into it.

**Comment by joffrey-bion** [comment]
@beenham could you please explain what it would bring to distribute module info with this library?
Is there anything you cannot do (or that is inconvenient) at the moment due to the lack of module declaration?

**Comment by oxodao** [comment]
If I'm not mistaken, the library in its current state can only be used with non-modular project.
To use it with modular projet we might need to add special flag to the JVM starting script which would be inconvenient for the end user

**Comment by joffrey-bion** [comment]
@oxodao Thanks a lot for the info, I will see what I can do then and report here.
Of course, PRs are welcome.
