### ISSUE TITLE
When I try to use the libary, I get: Kotlin: Module org.hildan.fxgson cannot be found in the module graph

### ISSUE THREAD

**Issue by BenHerbst** [joffrey-bion/fx-gson#21]
When I try to require the libary in my module-info, I get the error: Kotlin: Module org.hildan.fxgson cannot be found in the module graph

**Comment by joffrey-bion** [comment]
Hi, thanks for reporting this! Could you please give a bit more information about your use case?
Which JDK version are you using? Are you using Kotlin? Gradle?

I wouldn't advise using Gson with Kotlin in general (also Gson itself is not really maintained anymore). If you're using Kotlin, Kotlinx Serialization would be more appropriate, or Moshi if you want something that feels like Gson.

**Comment by joffrey-bion** [comment]
I think this is an issue with Gradle when using Kotlin+a modular dependency. See https://github.com/gradle/gradle/issues/17271.

I'm not sure there is anything I can/should do on this library's side.
