### ISSUE TITLE
Just a Thank You

### ISSUE THREAD

**Issue by SimGitTest** [joffrey-bion/fx-gson#22]
Hello,

I was really struggling with trying to figure out how to serialize one of my classes into Json that contained a bunch of JavaFX Color objects and saw your answer to a post in StackOverflow linking to your library and the library made it SO SIMPLE ... so ... THANK YOU for writing this library.  ☺

**Comment by EasyG0ing1** [comment]
Sorry I was logged in under a test account when I created this ... I've been working on getting a stable release out for my project, [GistFX](https://github.com/RedmondSims/GistFX) which is the project I'm using your library in incidentally.

**Comment by joffrey-bion** [comment]
Thanks a lot for your feedback! This is really appreciated, and I'm happy to have helped at least a few people like you with this tiny library 😊
