### ISSUE TITLE
ObjectProperty<File>

### ISSUE THREAD

**Issue by wesosdqueso** [joffrey-bion/fx-gson#27]
Adding a default out of the box adapter for `ObjectProperty<File>` would be handy.

I was getting "java.base does not opens java.io to gson" error.

```
import java.io.File;
import java.io.IOException;

import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonToken;
import com.google.gson.stream.JsonWriter;

public class FileAdapter extends TypeAdapter<File>{

	@Override
	public void write(JsonWriter out, File value) throws IOException {
		if(value==null) {
			out.nullValue();
			return;
		}
		out.value(value.toString());
	}

	@Override
	public File read(JsonReader in) throws IOException {
		if(in.peek() == JsonToken.NULL) {
			in.nextNull();
			return null;
		}
		return new File(in.nextString());		
	}

}
```

**Comment by joffrey-bion** [comment]
But back to the original question, there is actually already a default type adapter for `ObjectProperty`. This type adapter delegates to `Gson` for the serialization of the object inside the property. So most likely you would get the same issue if you tried to serialize a `File` field directly, and technically you only need something custom for `File`, not for `ObjectProperty<File>`, which is what you seem to be suggesting here in your proposed implementation.

This begs the question, though, is this really an FX Gson responsibility or a Gson responsibility?

Also, note that you don't need a type adapter per se in this case, maybe just a `JsonSerializer<File>`/`JsonDeserializer<File>` (which wouldn't be called on null values, so it can focus on the non-null case):

```kotlin
public class FileSerializer implements JsonSerializer<File>, JsonDeserializer<File> {
    @Override
    public JsonElement serialize(File src, Type typeOfSrc, JsonSerializationContext context) {
        return new JsonPrimitive(src.getPath());
    }

    @Override
    public File deserialize(JsonElement json, Type typeOfT, JsonDeserializationContext context) throws JsonParseException {
        return new File(json.getAsString());
    }
}
```

**Comment by joffrey-bion** [comment]
Closing this issue as `wontfix` because provided a type adapter or serializer for the `File` type is unrelated to this library.

If you think this is useful, please report the issue to the `Gson` library itself.
