### ISSUE TITLE
Can't fetch project via maven.

### ISSUE THREAD

**Issue by cguckes** [joffrey-bion/fx-gson#4]
Currently there seems to be no release on any of the default maven repositories. Is it located in a different repository or am I doing anything wrong?

**Comment by cguckes** [comment]
Didn't figure out that it was on bintray, resolved.

**Comment by joffrey-bion** [comment]
I'm glad you found the issue. I'll put a warning in the maven section of the readme to make sure people don't struggle anymore.

**Comment by brian070** [comment]
I still am struggling with the same problem. I added the settings.xml file that your link provided and then added your project as a dependency, but when importing the project it doesn't load it.
